edition = "2018"
hard_tabs = true
max_width = 100

enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
